// ─────────────────────────────────────────────
//  CONFIG — edit this file to update your site
// ─────────────────────────────────────────────

export const CONFIG = {
  owner: {
    name: "YOUR NAME",
    tagline: "Photographer · Developer · Producer · Creator",
    bio: "Documenting the world through lenses, code, sound, and imagination. Based somewhere beautiful.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    social: {
      github:     "#",
      instagram:  "#",
      soundcloud: "#",
      email:      "hello@yourname.com",
    },
  },

  // ── Hero/background images per section ───────
  backgrounds: {
    home:        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=80",
    photography: "https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=1600&q=80",
    code:        "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=1600&q=80",
    music:       "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&q=80",
    creative:    "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=1600&q=80",
    blog:        "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1600&q=80",
  },

  // ── Photography ───────────────────────────────
  // Each entry: title, src, date (YYYY-MM-DD), location, camera, lens, tags[], description
  photography: [
    {
      id: 1,
      title: "Alpine Light",
      src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      date: "2024-07-14",
      location: "Swiss Alps, Switzerland",
      camera: "Sony A7IV",
      lens: "24-70mm f/2.8",
      tags: ["landscape", "mountains", "golden hour"],
      description: "Chasing the last light of summer at 3,000m elevation.",
    },
    {
      id: 2,
      title: "Tokyo Neon",
      src: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
      date: "2024-03-22",
      location: "Shinjuku, Tokyo, Japan",
      camera: "Fujifilm X-T5",
      lens: "35mm f/1.4",
      tags: ["street", "night", "urban"],
      description: "Lost in the electric city at midnight.",
    },
    {
      id: 3,
      title: "Desert Silence",
      src: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
      date: "2024-01-08",
      location: "Wadi Rum, Jordan",
      camera: "Sony A7IV",
      lens: "16-35mm f/2.8",
      tags: ["landscape", "desert", "minimal"],
      description: "Nothing but sand, rock, and infinite sky.",
    },
    {
      id: 4,
      title: "Forest Fog",
      src: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
      date: "2023-11-03",
      location: "Black Forest, Germany",
      camera: "Fujifilm X-T5",
      lens: "56mm f/1.2",
      tags: ["forest", "mist", "nature"],
      description: "Dawn mist weaving between ancient pines.",
    },
    {
      id: 5,
      title: "Coastal Geometry",
      src: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80",
      date: "2023-09-17",
      location: "Faroe Islands, Denmark",
      camera: "Sony A7IV",
      lens: "24-70mm f/2.8",
      tags: ["coastal", "aerial", "abstract"],
      description: "The islands carved like sculptures from the North Atlantic.",
    },
    {
      id: 6,
      title: "Portrait — Studio",
      src: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80",
      date: "2024-05-30",
      location: "Berlin, Germany",
      camera: "Sony A7IV",
      lens: "85mm f/1.4",
      tags: ["portrait", "studio", "light"],
      description: "Exploring shadow and light with a single strobe.",
    },
  ],

  // ── Code Projects ─────────────────────────────
  codeProjects: [
    {
      id: 1,
      title: "Synthwave",
      subtitle: "Generative Music Engine",
      description: "A browser-based synthesizer that generates ambient music using procedural algorithms and WebAudio API. Built with React and Tone.js.",
      stack: ["React", "Tone.js", "WebAudio API", "Canvas"],
      status: "live",
      progress: 90,
      link: "#",
      github: "#",
      year: "2024",
      color: "#7a9e6c",
    },
    {
      id: 2,
      title: "Aperture",
      subtitle: "Photo Metadata Manager",
      description: "CLI tool and web UI for batch-processing EXIF data, auto-geotagging, and organizing large photo libraries by location and date.",
      stack: ["Python", "FastAPI", "React", "SQLite"],
      status: "in-progress",
      progress: 65,
      link: "#",
      github: "#",
      year: "2024",
      color: "#c4a87c",
    },
    {
      id: 3,
      title: "Terrain",
      subtitle: "3D Map Generator",
      description: "Procedural terrain generation using simplex noise, rendered with Three.js. Export to PNG or interactive web embed.",
      stack: ["Three.js", "WebGL", "GLSL", "Node.js"],
      status: "live",
      progress: 100,
      link: "#",
      github: "#",
      year: "2023",
      color: "#9e7a58",
    },
    {
      id: 4,
      title: "Chronicle",
      subtitle: "Creative Project Tracker",
      description: "Personal tool for tracking long-term creative projects — photography expeditions, albums, and builds — with timeline visualization.",
      stack: ["SvelteKit", "D3.js", "PostgreSQL"],
      status: "planning",
      progress: 15,
      link: "#",
      github: "#",
      year: "2025",
      color: "#8a9e8a",
    },
  ],

  // ── Music Projects ────────────────────────────
  musicProjects: [
    {
      id: 1,
      title: "Solstice EP",
      genre: "Ambient / Electronic",
      year: "2024",
      tracks: 5,
      status: "released",
      cover: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80",
      description: "Five pieces inspired by the interplay of light and darkness during midsummer. Recorded over three weeks in a rented mountain cabin.",
      tools: ["Ableton Live", "Moog Subsequent 37", "Roland SP-404", "Field Recordings"],
      link: "#",
    },
    {
      id: 2,
      title: "Urban Textures Vol. 1",
      genre: "Experimental / Field Recording",
      year: "2024",
      tracks: 8,
      status: "released",
      cover: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80",
      description: "Eight compositions built entirely from field recordings captured across Tokyo, Berlin, and New York. City as instrument.",
      tools: ["Zoom H6", "Max/MSP", "Ableton Live", "Granular Synthesis"],
      link: "#",
    },
    {
      id: 3,
      title: "Untitled Album",
      genre: "Post-Rock / Instrumental",
      year: "2025",
      tracks: 7,
      status: "in-progress",
      cover: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&q=80",
      description: "Working on a longer-form project blending live guitar, modular synthesis, and orchestral samples. ETA: late 2025.",
      tools: ["Ableton Live", "Guitar", "Eurorack", "Spitfire LABS"],
      link: "#",
    },
  ],

  // ── Creative / Misc Projects ──────────────────
  creativeProjects: [
    {
      id: 1,
      title: "Darkroom Prints",
      category: "Analog Photography",
      year: "2023–2024",
      status: "ongoing",
      image: "https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?w=600&q=80",
      description: "Traditional silver gelatin darkroom printing. Learning to control light and chemistry by hand. Each print is unique.",
      progress: 70,
    },
    {
      id: 2,
      title: "Zine — Vol. 1",
      category: "Print / Editorial",
      year: "2024",
      status: "released",
      image: "https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?w=600&q=80",
      description: "A 48-page hand-assembled photography and writing zine. 50 copies printed on a Risograph. Sold out in two weeks.",
      progress: 100,
    },
    {
      id: 3,
      title: "Video Essay Series",
      category: "Film / Essay",
      year: "2025",
      status: "in-progress",
      image: "https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=600&q=80",
      description: "Long-form video essays on creative process, place, and craft. Episode 1 in post-production.",
      progress: 35,
    },
  ],

  // ── Blog / Journal Posts ──────────────────────
  blogPosts: [
    {
      id: 1,
      title: "On Shooting in the Rain",
      date: "2024-11-15",
      category: "Photography",
      excerpt: "Why I've started actively seeking out the worst weather for my best photographs — and what I've learned from being miserable and soaked.",
      readTime: "7 min",
      content: `There's a particular quality of light that only exists during and after rain. The way wet pavement mirrors the sky. The way colors saturate beyond their usual range.\n\nI used to pack my camera away at the first sign of clouds. Now I do the opposite — I check the forecast and head out when everyone else is staying inside.\n\n**The Gear Question**\n\nYou don't need weather-sealed equipment to shoot in the rain. You need a cheap $8 shower cap and the willingness to get a little wet. That said, if you're shooting consistently in harsh conditions, weather sealing matters.\n\n**What Rain Does to Light**\n\nOvercast skies act as a giant softbox. Harsh shadows disappear. Skin tones become even and flattering. Cityscapes glow with reflected neon. Rain creates a diffused, cinematic quality that golden hour can't replicate.\n\n**The Practical Approach**\n\nStart by shooting from covered positions — under awnings, from inside cafes looking out. Get comfortable with the visual language of wet scenes. Then gradually push further into the conditions.\n\nThe best images from the past year have all been taken in weather that made me question why I left the house.`,
      tags: ["technique", "weather", "street photography"],
    },
    {
      id: 2,
      title: "Building Synthwave: Six Months In",
      date: "2024-10-02",
      category: "Code",
      excerpt: "A progress update on my generative music engine project — what worked, what failed spectacularly, and where it's going.",
      readTime: "12 min",
      content: `Six months ago I started building a browser-based generative music engine. Here's what I've learned.\n\n**The Original Vision**\n\nI wanted something that would generate ambient music procedurally — something you could leave running in a browser tab that would never repeat itself. Meditative, algorithmic, evolving.\n\n**What Actually Happened**\n\nThe first two months were spent on architecture decisions I'd later undo. I over-engineered the state management before I had any sound working. Classic mistake.\n\n**The Breakthrough**\n\nMonth three: I threw out the elaborate state machine and started with the simplest possible thing — one oscillator, one reverb, one note at a time. From that foundation, adding complexity became fun instead of a chore.\n\n**Current State**\n\nThe engine now handles polyphony, procedural chord progressions using music theory constraints, a Markov chain for melodic generation, and real-time parameter modulation. It actually sounds good.\n\n**What's Next**\n\nThe UI needs work. The engine is solid — the experience of using it is still too technical. Next milestone: make it accessible to someone who doesn't know what a Markov chain is.`,
      tags: ["web audio", "generative music", "react", "progress update"],
    },
    {
      id: 3,
      title: "The Solstice EP — Production Notes",
      date: "2024-08-20",
      category: "Music",
      excerpt: "Track-by-track notes on how the Solstice EP came together in a cabin with no WiFi and a lot of time to think.",
      readTime: "9 min",
      content: `Three weeks. A rented cabin at 1,400m. No internet connection. Five tracks.\n\n**The Setup**\n\nI brought the Moog, a laptop, the SP-404, and a Zoom H6 for field recordings. The cabin had a wood stove and a view of the valley. The nearest town was 40 minutes away.\n\n**Track 1 — Arrival**\n\nRecorded on the first afternoon. Field recordings from the drive up — car engine, gravel roads, wind through the window. Processed through heavy reverb and granular stretching. The Moog provides a single sustained bass note. That's it.\n\n**Track 2 — Solstice**\n\nThe centrepiece. Built around a chord progression I found while noodling on the second night. Total runtime: 11 minutes.\n\n**The Unexpected**\n\nOn day 8, a thunderstorm rolled through and knocked out power for six hours. I recorded the whole thing through the H6. Three minutes of that recording ended up in Track 4.\n\n**What I Learned**\n\nConstraints are generative. No internet meant no distraction-driven research spirals. No gear store nearby meant working with what I had. The limitations made the album what it is.`,
      tags: ["ambient", "production", "process", "EP"],
    },
    {
      id: 4,
      title: "Why I Still Shoot Film",
      date: "2024-06-10",
      category: "Photography",
      excerpt: "It's slower, more expensive, and the results are less predictable. Here's why I keep doing it anyway.",
      readTime: "5 min",
      content: `Every so often someone asks me why I bother with film in 2024. Here's the honest answer.\n\n**It's Not Nostalgia**\n\nI'm not shooting film because I wish it was 1975. I'm shooting film because the constraints change how I see and how I shoot.\n\n**36 Exposures**\n\nWhen you have 36 frames on a roll and each one costs real money to develop and scan, you slow down. You wait for the right light. You reconsider before you fire the shutter.\n\n**The Grain**\n\nDigital noise and film grain are not the same thing. Film grain has organic structure — it's beautiful in a way that digital noise simply isn't.\n\n**The Surprise**\n\nDigital photography gives you instant feedback. Film photography gives you anticipation. Opening a freshly developed roll is a particular kind of joy.\n\n**The Honest Part**\n\nFilm is expensive and slow and sometimes frustrating. Half of what I shoot doesn't work. But the other half looks like nothing else I make.`,
      tags: ["film", "analog", "process"],
    },
  ],
};
